#!/usr/bin/env python
#-*-coding: utf-8-*-

# Version: 0.1
# Author: Anson Tang <anson.tkg@gmail.com>
# License: Copyright(c) 2015 Anson.Tang
# Summary: 

HASH_NICKNAME_REGISTERED = 'HASH_NICKNAME_REGISTERED'
HASH_MACHINE_CODE_REGISTERED = 'HASH_MACHINE_CODE_REGISTERED'
HASH_UID_MACHINE_CODE = 'HASH_UID_MACHINE_CODE'

SET_RANK_PVP_WEIGHT = 'SET_RANK_PVP_WEIGHT'
SER_RANK_PVP_EAT = 'SER_RANK_PVP_EAT'
SER_RANK_PVP_EATED = 'SER_RANK_PVP_EATED'

SER_RANK_ROOM_VOLUME = 'SER_RANK_ROOM_VOLUME_%s'
SER_RANK_ROOM_EAT = 'SER_RANK_ROOM_EAT_%s'
SER_RANK_ROOM_EATED = 'SER_RANK_ROOM_EATED_%s'
